force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <defaultValue>&apos;상담고객&apos;</defaultValue>
    <label>고객유형</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>이메일</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstBranch__c.field-meta.xml
<CustomField>
    <fullName>FirstBranch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>첫 구매를 진행한 지점</description>
    <label>인입지점</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Branch__c.Name</field>
            <operation>contains</operation>
            <valueField>$User.Department</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last90DaysTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>Last90DaysTotalPrice__c</fullName>
    <label>최근3개월누적금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>전화번호 기입</description>
    <label>전화번호</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SupportTier__c.field-meta.xml
<CustomField>
    <fullName>SupportTier__c</fullName>
    <defaultValue>$CustomMetadata.CustomerTier__mdt.D.MasterLabel</defaultValue>
    <label>고객 등급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>총구매금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountController.cls
public with sharing class AccountController {
    @AuraEnabled(cacheable=true)
    public static String getPhoneByAccountId(Id accountId) {
        try {
            Account account = [SELECT Id, Phone__c, SupportTier__c FROM Account WHERE Id = :accountId];
            return account.Phone__c;
        } catch (QueryException e) {
            // 쿼리 중 발생한 예외를 처리
            System.debug('QueryException: ' + e.getMessage());
            return null; 
        } catch (Exception e) {
            // 그 외 예외 처리
            System.debug('Exception: ' + e.getMessage());
            return null;
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccounts(String searchKeyword) {
        if (String.isNotBlank(searchKeyword)) {
            return [SELECT Id, Name, Phone__c, SupportTier__c, AccountType__c, Email__c, FirstBranch__c, TotalPrice__c, Last90DaysTotalPrice__c FROM Account WHERE Name LIKE :('%'+searchKeyword+'%')];
        } else {
            return [SELECT Id, Name, Phone__c, SupportTier__c, AccountType__c, Email__c, FirstBranch__c, TotalPrice__c, Last90DaysTotalPrice__c FROM Account];
        }
    }
    
    @AuraEnabled
    public static void updateContactPhone(String accountId, String phone) {
        Account account = [SELECT Id, Phone__c FROM Account WHERE Id = :accountId LIMIT 1];
        account.Phone__c = phone;
        update account;
    }

    }