force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>이메일</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SangDam__c/SangDam__c.object-meta.xml
<CustomObject>
    <label>상담</label>
    <nameField>
        <displayFormat>상담-{000000}</displayFormat>
        <label>상담 번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SangDam__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>고객명</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SangDam__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>이메일주소 입력</description>
    <label>이메일</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SangDam__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <inlineHelpText>휴대번호 입력시 010-XXXX-XXXX 형식으로 입력해야합니다.
010외 011, 017 등 01X로 입력시 고객정보 생성이 불가능합니다.</inlineHelpText>
    <label>전화번호</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SangDam__c/fields/ProductList__c.field-meta.xml
<CustomField>
    <fullName>ProductList__c</fullName>
    <label>상품명</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>아이디어패드 Slim3</fullName>
            </value>
            <value>
                <fullName>2024 그램15</fullName>
            </value>
            <value>
                <fullName>Sword GF76</fullName>
            </value>
            <value>
                <fullName>2023 그램15</fullName>
            </value>
            <value>
                <fullName>젠북 14 OLED</fullName>
            </value>
            <value>
                <fullName>2024 그램16</fullName>
            </value>
            <value>
                <fullName>갤럭시북4 프로</fullName>
            </value>
            <value>
                <fullName>갤럭시북3</fullName>
            </value>
            <value>
                <fullName>프레데터 Helios Neo</fullName>
            </value>
            <value>
                <fullName>아이디어패드 Slim1</fullName>
            </value>
            <value>
                <fullName>키보드 K560</fullName>
            </value>
            <value>
                <fullName>키보드 F99</fullName>
            </value>
            <value>
                <fullName>키보드 CK01</fullName>
            </value>
            <value>
                <fullName>키보드 G413</fullName>
            </value>
            <value>
                <fullName>키보드 GK893B</fullName>
            </value>
            <value>
                <fullName>마우스 SUPERLIGHT</fullName>
            </value>
            <value>
                <fullName>마우스 MX Master</fullName>
            </value>
            <value>
                <fullName>마우스 DeathAdder</fullName>
            </value>
            <value>
                <fullName>마우스 M1300QB</fullName>
            </value>
            <value>
                <fullName>마우스 G102</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SangDam__c/fields/SangDamDate__c.field-meta.xml
<CustomField>
    <fullName>SangDamDate__c</fullName>
    <label>상담일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SangDam__c/fields/SangDamDescription__c.field-meta.xml
<CustomField>
    <fullName>SangDamDescription__c</fullName>
    <description>상담내역 기입란</description>
    <label>상담내역</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SangDam__c/fields/SangDamProgress__c.field-meta.xml
<CustomField>
    <fullName>SangDamProgress__c</fullName>
    <description>상담 진행현황 표시</description>
    <label>상담 진행현황</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>단순상담</fullName>
                <default>true</default>
                <label>단순상담</label>
            </value>
            <value>
                <fullName>구매조건 확인</fullName>
            </value>
            <value>
                <fullName>상담완료</fullName>
            </value>
            <value>
                <fullName>구매물품 견적</fullName>
                <isActive>false</isActive>
                <label>구매물품 견적</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SangDam__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>상담지점</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>울산점</fullName>
            </value>
            <value>
                <fullName>세종점</fullName>
            </value>
            <value>
                <fullName>서울강남점</fullName>
            </value>
            <value>
                <fullName>부산센텀시티점</fullName>
            </value>
            <value>
                <fullName>대구점</fullName>
            </value>
            <value>
                <fullName>광주점</fullName>
            </value>
            <value>
                <fullName>인천점</fullName>
            </value>
            <value>
                <fullName>대전점</fullName>
            </value>
            <value>
                <fullName>광주광역시</fullName>
                <isActive>false</isActive>
                <label>광주광역시</label>
            </value>
            <value>
                <fullName>대구광역시</fullName>
                <isActive>false</isActive>
                <label>대구광역시</label>
            </value>
            <value>
                <fullName>대전광역시</fullName>
                <isActive>false</isActive>
                <label>대전광역시</label>
            </value>
            <value>
                <fullName>부산광역시</fullName>
                <isActive>false</isActive>
                <label>부산광역시</label>
            </value>
            <value>
                <fullName>서울특별시</fullName>
                <isActive>false</isActive>
                <label>서울특별시</label>
            </value>
            <value>
                <fullName>세종특별자치시</fullName>
                <isActive>false</isActive>
                <label>세종특별자치시</label>
            </value>
            <value>
                <fullName>울산광역시</fullName>
                <isActive>false</isActive>
                <label>울산광역시</label>
            </value>
            <value>
                <fullName>인천광역시</fullName>
                <isActive>false</isActive>
                <label>인천광역시</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SangDamController.cls
public with sharing class SangDamController {
    @AuraEnabled(cacheable=true)
    public static List<SangDam__c> getSangDams(String customerName) {
        if (String.isNotBlank(customerName)) {
            return [SELECT Id, AccountName__c, SangDamDate__c, SangDamProgress__c, SangdamDescription__c, ProductList__c
                    FROM SangDam__c
                    WHERE AccountName__c LIKE :('%' + customerName + '%')];
        } else {
            return [SELECT Id, AccountName__c,  SangDamDate__c, SangDamProgress__c, SangdamDescription__c, productlist__c
                    FROM SangDam__c];
        }
    }

    @AuraEnabled
    public static SangDam__c updateSangDam(SangDam__c updatedSangDam) {
        try {
            update updatedSangDam;
            return updatedSangDam;
        } catch (Exception e) {
            throw new AuraHandledException('Update Error: ' + e.getMessage());
        }
    }
        @AuraEnabled(cacheable=true)
        public static List<SangDam__c> getSangDamRecordsMatchingAccountName(Id accountId) {
            List<Account> accounts = [SELECT Id, Name FROM Account WHERE Id = :accountId];
            if (!accounts.isEmpty()) {
                String accountName = accounts[0].Name;
                
                return [
                    SELECT Id, Name, SangDamDate__c, SangDamProgress__c, StoreName__c, 
                           ProductList__c, Email__c, PhoneNumber__c
                    FROM SangDam__c 
                    WHERE AccountName__c = :accountName
                ];
            }
            return new List<SangDam__c>();
        }
    }