force-app/main/default/objects/Account/fields/FirstBranch__c.field-meta.xml
<CustomField>
    <fullName>FirstBranch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>첫 구매를 진행한 지점</description>
    <label>인입지점</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Branch__c.Name</field>
            <operation>contains</operation>
            <valueField>$User.Department</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/LeadContentsCnt__c.field-meta.xml
<CustomField>
    <fullName>LeadContentsCnt__c</fullName>
    <defaultValue>0</defaultValue>
    <label>상담횟수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/SupportTier__c.field-meta.xml
<CustomField>
    <fullName>SupportTier__c</fullName>
    <defaultValue>$CustomMetadata.CustomerTier__mdt.D.MasterLabel</defaultValue>
    <label>고객 등급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>총구매금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomerController.cls
public with sharing class CustomerController {
    @AuraEnabled(cacheable=true)
    public static List<Account> searchCustomers(String partialPhoneNumber){
        String phoneQuery = '%' + partialPhoneNumber + '%';
        return [SELECT Id, Name, Phone, SupportTier__c, 
                FirstBranch__c, TotalPrice__c, LeadContentsCnt__c FROM Account WHERE Phone LIKE :phoneQuery];
    }

    @AuraEnabled(cacheable=true)
    public static Account getCustomerDetails(Id accountId){
        return [SELECT Id, Name, Phone, SupportTier__c, 
        FirstBranch__c, TotalPrice__c, LeadContentsCnt__c FROM Account WHERE ID = : accountId LIMIT 1 ];
    }
}