force-app/main/default/objects/Account/fields/FirstBranch__c.field-meta.xml
<CustomField>
    <fullName>FirstBranch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>첫 구매를 진행한 지점</description>
    <label>인입지점</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Branch__c.Name</field>
            <operation>contains</operation>
            <valueField>$User.Department</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>전화번호 기입</description>
    <label>전화번호</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SupportTier__c.field-meta.xml
<CustomField>
    <fullName>SupportTier__c</fullName>
    <defaultValue>$CustomMetadata.CustomerTier__mdt.D.MasterLabel</defaultValue>
    <label>고객 등급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>총구매금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>지역별 판매점</description>
    <label>판매점</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountClass.cls
public with sharing class AccountClass { //홈 본사에서 보는 Showaccout 컴포넌트에 띄울 메서드
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccounts(String searchTextClass){
        try{
            if(String.isEmpty(searchTextClass))
            {
            return [SELECT Id, Name, Phone__c FROM Account];
            }
            else {
                {
                    searchTextClass = '%' + searchTextClass + '%';
                    return [ SELECT Id, Name, Phone__c FROM Account WHERE Phone__c Like : searchTextClass];
                }
            }
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Account>  getAccountInfo(String accountId){
        try {
            return [SELECT Id, Name, Phone__c, SupportTier__c,FirstBranch__r.Name,TotalPrice__c   FROM Account WHERE Id = : accountId ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}