force-app/main/default/objects/Account/fields/FirstBranch__c.field-meta.xml
<CustomField>
    <fullName>FirstBranch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>첫 구매를 진행한 지점</description>
    <label>인입지점</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Branch__c.Name</field>
            <operation>contains</operation>
            <valueField>$User.Department</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/OrderHistory__c.object-meta.xml
<CustomObject>
    <label>주문내역</label>
    <nameField>
        <displayFormat>주문-{000000}</displayFormat>
        <label>주문번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHistory__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>주문내역</relationshipLabel>
    <relationshipName>AccHistoryNames</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/SalesBranch__c.field-meta.xml
<CustomField>
    <fullName>SalesBranch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>판매점</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$User.Department</field>
            <operation>equals</operation>
            <valueField>Branch__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eIR000001fnLEYAY</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>주문내역</relationshipLabel>
    <relationshipName>SalesBranches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountFirstBranchManager.cls
public with sharing class AccountFirstBranchManager {

    // 첫 구매에 따라 고객의 인입지점 업데이트
    public static void updateFirstBranch(List<OrderHistory__c> newOrders) {
    // 새 주문과 연관된 고객 계정 ID 수집
    Set<Id> accountIds = new Set<Id>();
    for(OrderHistory__c order : newOrders) {
        if(order.AccountName__c != null) {
            accountIds.add(order.AccountName__c);
        }
    }

    // 인입지점이 설정되지 않은 계정만 필터링
    Map<Id, Account> accountsToUpdate = new Map<Id, Account>();
    for(Account acc : [SELECT Id, FirstBranch__c FROM Account WHERE Id IN :accountIds AND FirstBranch__c = null]) {
        accountsToUpdate.put(acc.Id, acc);
    }

    // 새 주문의 판매점 정보로 인입지점 업데이트
    for(OrderHistory__c order : newOrders) {
        if(accountsToUpdate.containsKey(order.AccountName__c) && order.SalesBranch__c != null) {
            accountsToUpdate.get(order.AccountName__c).FirstBranch__c = order.SalesBranch__c;
        }
    }

    update accountsToUpdate.values();
    }
    
}