force-app/main/default/objects/Account/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>전화번호 기입</description>
    <label>전화번호</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>총구매금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>지역별 판매점</description>
    <label>판매점</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/SalesRep__c.field-meta.xml
<CustomField>
    <fullName>SalesRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>판매사원</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>판매사원</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepngBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/OrderHistory__c.object-meta.xml
<CustomObject>
    <label>주문내역</label>
    <nameField>
        <displayFormat>주문-{000000}</displayFormat>
        <label>주문번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHistory__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>주문내역</relationshipLabel>
    <relationshipName>AccHistoryNames</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/AccountPhone__c.field-meta.xml
<CustomField>
    <fullName>AccountPhone__c</fullName>
    <label>고객전화번호</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/BeforeDiscount__c.field-meta.xml
<CustomField>
    <fullName>BeforeDiscount__c</fullName>
    <label>판매금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <label>할인율</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/DiscountPrice__c.field-meta.xml
<CustomField>
    <fullName>DiscountPrice__c</fullName>
    <label>할인금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>판매일자</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/OrderDetail__c.field-meta.xml
<CustomField>
    <fullName>OrderDetail__c</fullName>
    <inlineHelpText>제품명1: 수량, 제품명2: 수량, ...</inlineHelpText>
    <label>상세내역</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/SalesBranch__c.field-meta.xml
<CustomField>
    <fullName>SalesBranch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>판매점</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$User.Department</field>
            <operation>equals</operation>
            <valueField>Branch__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eIR000001fnLEYAY</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>주문내역</relationshipLabel>
    <relationshipName>SalesBranches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/SaleStatus__c.field-meta.xml
<CustomField>
    <fullName>SaleStatus__c</fullName>
    <label>판매상태</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>판매완료</fullName>
                <default>true</default>
                <label>판매완료</label>
            </value>
            <value>
                <fullName>환불완료</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>실판매금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/OrderProduct__c.object-meta.xml
<CustomObject>
    <label>주문제품</label>
    <nameField>
        <label>제품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderProduct__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>주문번호</label>
    <referenceTo>OrderHistory__c</referenceTo>
    <relationshipLabel>주문제품</relationshipLabel>
    <relationshipName>HistoryProductNumbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>제품코드</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/ProductQuantity__c.field-meta.xml
<CustomField>
    <fullName>ProductQuantity__c</fullName>
    <label>제품수량</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>제품타입</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/SalePStatus__c.field-meta.xml
<CustomField>
    <fullName>SalePStatus__c</fullName>
    <label>판매상태</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>판매완료</fullName>
                <default>true</default>
                <label>판매완료</label>
            </value>
            <value>
                <fullName>환불완료</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/SalesBranch__c.field-meta.xml
<CustomField>
    <fullName>SalesBranch__c</fullName>
    <formula>OrderNumber__r.SalesBranch__r.Name</formula>
    <label>판매점</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>제품가격</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>제품 정보</description>
    <label>제품</label>
    <nameField>
        <label>제품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <description>제품별 코드</description>
    <label>제품코드</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>제품타입</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>노트북</fullName>
            </value>
            <value>
                <fullName>주변기기</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>제품가격</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductType__c/ProductType__c.object-meta.xml
<CustomObject>
    <label>제품유형</label>
    <nameField>
        <label>ProductType Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderService.cls
public with sharing class OrderService {
    
    // 제품 목록 조회 메소드
    @AuraEnabled(cacheable=true)
    public static List<Product__c> getProducts() {
        // 모든 제품 정보 조회 SOQL 쿼리
        return [SELECT Id, Name, UnitPrice__c, ProductCode__c, ProductType__c FROM Product__c];
    }    

    // 특정 제품의 상세 정보 조회 메소드
    @AuraEnabled(cacheable=true)
    public static Product__c getProductDetail(Id productId) {
        // 제품 ID를 기반으로 한 제품 상세 정보 조회 SOQL 쿼리
        return [SELECT Id, Name, UnitPrice__c, ProductCode__c, ProductType__c FROM Product__c WHERE Id = :productId LIMIT 1];
    }

    // 주문 생성 메소드
    @AuraEnabled
    public static void createOrder(string accountId, List<String> productIds, List<Integer> quantities, Decimal discountPercent, Date orderDate) {

        // getUserRoleId() 컨텍스트 사용자의 역할 ID를 반환합니다. 
        // UserRole uRole = [SELECT Name FROM UserRole WHERE Id = :UserInfo.getUserRoleId()];
        // String currentUserName = UserInfo.getName();

        // 현재 사용자의 정보 조회
        String currentUserId = UserInfo.getUserId();

        // 현재 사용자의 역할 이름 조회
        String currentUserRoleName = [SELECT Name FROM UserRole WHERE Id = :UserInfo.getUserRoleId()].Name;
        Branch__c matchingBranch;

        String adminRoleName = 'System Admin';

        // 사용자 역할에 따라 다른 처리 로직 적용
        if (currentUserRoleName == adminRoleName) {
            // 관리자의 경우, 특정 판매점 할당
            matchingBranch = [SELECT Id, Name FROM Branch__c WHERE Id = 'a01IR00001fVDQ3YAO' LIMIT 1];
        } else {
            // 일반 사용자의 경우, 사용자에게 할당된 판매점 조회
            matchingBranch = [SELECT Id FROM Branch__c WHERE SalesRep__c = :currentUserId  LIMIT 1];
        }

        // 판매정보를 입력한 고객의 정보
        Account accountInfo = [SELECT Id, Name, Phone__c FROM Account WHERE Id = :accountId LIMIT 1];

        // 주문 상세 및 가격 계산 로직
        Decimal totalAmount = 0;
        List<String> orderDetail = new List<String>();

        for(Integer i = 0; i < productIds.size(); i++) {
            Id productId = productIds[i];
            Integer quantity = quantities[i];

            Product__c product = [SELECT Id, Name, UnitPrice__c, ProductType__c FROM Product__c WHERE Id = :productId LIMIT 1];

            String formattedPrice = formatCurrency(product.UnitPrice__c);

            String detail = product.Name + ' (' + formattedPrice + ') - 수량: ' + quantities[i];
            orderDetail.add(detail);

            totalAmount += product.UnitPrice__c * quantity;
        }

        // 할인 계산 및 최종 금액 계산
        Decimal discountAmount = totalAmount * (discountPercent / 100);
        Decimal finalAmount = totalAmount - discountAmount;

        // 주문 내역 정보 합치기
        String orderLists = String.join(orderDetail, ', \n');

        String saleCompletedStatus = '판매완료'; // 상태 값을 변수에 할당

        // 주문 내역 레코드 생성 및 저장
        List<OrderHistory__c> newOH = new List<OrderHistory__c>();
        OrderHistory__c oh = new OrderHistory__c(
             // 주문 내역 필드 값 할당
            OrderDate__c = orderDate,
            OrderDetail__c = orderLists,
            BeforeDiscount__c = totalAmount,
            TotalPrice__c = finalAmount,
            DiscountPercent__c = discountPercent,
            DiscountPrice__c = discountAmount,
            SalesBranch__c = matchingBranch.Id,
            AccountName__c = accountInfo.Id,
            AccountPhone__c = accountInfo.Phone__c,
            SaleStatus__c = saleCompletedStatus
        );
        newOH.add(oh);

        insert newOH; 


        String salePCompletedStatus = '판매완료';

        // 판매등록 후 동시에 제품별 주문 레코드 생성 및 저장 로직
        List<OrderProduct__c> newOP = new List<OrderProduct__c>();
        // 반복문 내 제품 정보 조회 및 OrderProduct__c 레코드 생성
        for(Integer i = 0; i < productIds.size(); i++) {
            Id productId = productIds[i];
            Integer quantity = quantities[i]; // 이 수량만큼 OrderProduct__c 레코드 생성

            // 제품 정보 조회
            Product__c product = [SELECT Id, Name, UnitPrice__c, ProductType__c, ProductCode__c FROM Product__c WHERE Id = :productId LIMIT 1];
            
            // 각 제품마다 수량만큼 OrderProduct__c 레코드 생성
            for (Integer q = 0; q < quantity; q++) {
                OrderProduct__c op = new OrderProduct__c();
                op.OrderNumber__c = oh.Id; // OrderHistory__c 레코드의 ID
                op.Name = product.Name; // 제품 이름
                op.ProductQuantity__c = 1; // 요구사항에 따라 각 레코드의 수량은 1로 설정
                op.UnitPrice__c = product.UnitPrice__c;
                op.ProductType__c = product.ProductType__c;
                op.ProductCode__c = product.ProductCode__c;
                op.SalePStatus__c = salePCompletedStatus;
                newOP.add(op);
            }
        }

        if (!newOP.isEmpty()) {
            insert newOP; // 생성된 OrderProduct__c 레코드 저장
        }
    }

    // 금액을 포맷하는 유틸리티 메소드
    private static String formatCurrency(Decimal amount) {
        // 금액 포맷 로직
        return '₩' + amount.setScale(0).format();
    }


}