force-app/main/default/objects/Account/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>총구매금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/OrderHistory__c.object-meta.xml
<CustomObject>
    <label>주문내역</label>
    <nameField>
        <displayFormat>주문-{000000}</displayFormat>
        <label>주문번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHistory__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>주문내역</relationshipLabel>
    <relationshipName>AccHistoryNames</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>실판매금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderHistoryController.cls
public with sharing class OrderHistoryController {

    @AuraEnabled(cacheable=true)
    public static List<OrderHistory__c> getOrderHistories(String accountName) {
        // Account 이름으로 Account ID 찾기
        Set<Id> accountIds = new Set<Id>();
        if (String.isNotBlank(accountName)) {
            for (Account acc : [SELECT Id FROM Account WHERE Name LIKE :('%' + accountName + '%')]) {
                accountIds.add(acc.Id);
            }
        }

        // Account ID를 사용하여 OrderHistory__c 검색
        if (!accountIds.isEmpty()) {
            return [SELECT Id, Name, TotalPrice__c, AccountName__r.Name FROM OrderHistory__c WHERE accountName__c IN :accountIds];
        } else {
            return [SELECT Id, Name, TotalPrice__c, AccountName__r.Name FROM OrderHistory__c];
        }
    }
}