force-app/main/default/objects/Account/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>총구매금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/OrderHistory__c.object-meta.xml
<CustomObject>
    <label>주문내역</label>
    <nameField>
        <displayFormat>주문-{000000}</displayFormat>
        <label>주문번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHistory__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>주문내역</relationshipLabel>
    <relationshipName>AccHistoryNames</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/AccountPhone__c.field-meta.xml
<CustomField>
    <fullName>AccountPhone__c</fullName>
    <label>고객전화번호</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/OrderDetail__c.field-meta.xml
<CustomField>
    <fullName>OrderDetail__c</fullName>
    <inlineHelpText>제품명1: 수량, 제품명2: 수량, ...</inlineHelpText>
    <label>상세내역</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>실판매금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/OrderProduct__c.object-meta.xml
<CustomObject>
    <label>주문제품</label>
    <nameField>
        <label>제품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderProduct__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>주문번호</label>
    <referenceTo>OrderHistory__c</referenceTo>
    <relationshipLabel>주문제품</relationshipLabel>
    <relationshipName>HistoryProductNumbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>제품코드</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/ProductQuantity__c.field-meta.xml
<CustomField>
    <fullName>ProductQuantity__c</fullName>
    <label>제품수량</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>제품타입</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderProduct__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>제품가격</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductType__c/ProductType__c.object-meta.xml
<CustomObject>
    <label>제품유형</label>
    <nameField>
        <label>ProductType Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductService.cls
public with sharing class ProductService {
    @AuraEnabled
    public static String createOrder(String accountId, String orderJson){

		try {
			UserRole userRole = [SELECT Name FROM UserRole WHERE Id = :UserInfo.getUserRoleId()];
			Account matchingAccount = [SELECT Id FROM Account WHERE Name = :userRole.Name LIMIT 1];
			Account accountInfo = [SELECT Phone FROM Account WHERE Id = :accountId LIMIT 1];

            // 직렬화된 JSON 문자열을 기반으로 OrderData 객체를 파싱합니다.
            OrderData orderData = (OrderData) JSON.deserialize(orderJson, OrderData.class);


            // OrderHistory__c 레코드를 생성하고 필수 필드를 설정합니다.
            OrderHistory__c ord = new OrderHistory__c(
                TotalPrice__c = orderData.totalPrice,
                OrderDetail__c = orderData.orderDetail,
                AccountName__c = orderData.accountName,
                AccountPhone__c = orderData.accountPhone
            );
            insert ord; // 생성한 레코드를 삽입합니다.

            List<OrderProduct__c> oliList = new List<OrderProduct__c>();

            for(ProductOrderWrapper product : orderData.products){
                OrderProduct__c oli = new OrderProduct__c(
                    OrderNumber__c = ord.Id, // 'OrderHistory__c'와의 Lookup 관계를 설정
                    Name = product.Name,
                    UnitPrice__c = product.price,
                    ProductQuantity__c = product.quantity,
                    ProductCode__c = product.code,
                    ProductType__c = product.type
                );
                oliList.add(oli);
            }

            insert oliList; // 생성한 OrderProduct__c 레코드 리스트를 삽입합니다.
            
            return ord.Id;
        
        } catch(Exception e) {
            // 에러를 잡아서 에러 메시지를 반환합니다.
            return 'Error: ' + e.getMessage();
        }
    }

    // 주문과 관련된 모든 데이터를 포함하는 복합 객체를 정의합니다.
    public class OrderData {
        @AuraEnabled
        public List<ProductOrderWrapper> products;
        @AuraEnabled
        public Decimal totalPrice;
        @AuraEnabled
        public String orderDetail;
        @AuraEnabled
        public String accountName;
        @AuraEnabled
        public String accountPhone;
    }

    public class ProductOrderWrapper {
        @AuraEnabled
        public String Id;
        @AuraEnabled
        public Decimal price;
        @AuraEnabled
        public Integer quantity;
        @AuraEnabled
        public String Name;
        @AuraEnabled
        public String code;
        @AuraEnabled
        public String type;
    }
}