force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>지역별 판매점</description>
    <label>판매점</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>도시명</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seoul</fullName>
            </value>
            <value>
                <fullName>Busan</fullName>
            </value>
            <value>
                <fullName>Daegu</fullName>
            </value>
            <value>
                <fullName>Incheon</fullName>
            </value>
            <value>
                <fullName>Gwangju</fullName>
            </value>
            <value>
                <fullName>Daejeon</fullName>
            </value>
            <value>
                <fullName>Ulsan</fullName>
            </value>
            <value>
                <fullName>Sejong</fullName>
            </value>
            <value>
                <fullName>광주광역시</fullName>
                <isActive>false</isActive>
                <label>광주광역시</label>
            </value>
            <value>
                <fullName>대구광역시</fullName>
                <isActive>false</isActive>
                <label>대구광역시</label>
            </value>
            <value>
                <fullName>대전광역시</fullName>
                <isActive>false</isActive>
                <label>대전광역시</label>
            </value>
            <value>
                <fullName>부산광역시</fullName>
                <isActive>false</isActive>
                <label>부산광역시</label>
            </value>
            <value>
                <fullName>서울특별시</fullName>
                <isActive>false</isActive>
                <label>서울특별시</label>
            </value>
            <value>
                <fullName>세종특별자치시</fullName>
                <isActive>false</isActive>
                <label>세종특별자치시</label>
            </value>
            <value>
                <fullName>울산광역시</fullName>
                <isActive>false</isActive>
                <label>울산광역시</label>
            </value>
            <value>
                <fullName>인천광역시</fullName>
                <isActive>false</isActive>
                <label>인천광역시</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>국가명</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SouthKorea</fullName>
            </value>
            <value>
                <fullName>I2maxCountry</fullName>
            </value>
            <value>
                <fullName>SalesforceCountry</fullName>
            </value>
            <value>
                <fullName>대한민국</fullName>
                <isActive>false</isActive>
                <label>대한민국</label>
            </value>
            <value>
                <fullName>세일즈포스국</fullName>
                <isActive>false</isActive>
                <label>세일즈포스국</label>
            </value>
            <value>
                <fullName>아이투맥스국</fullName>
                <isActive>false</isActive>
                <label>아이투맥스국</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>지번</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>주소</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MapController.cls
public with sharing class MapController {
   
    @AuraEnabled(cacheable=true)
    public static List<Branch__c> getStore(){
        try {
            //branch 오브젝트에서 주소 정보가져오기 
           return  [SELECT Id, Name, City__c, Country__c, Street__c, PostalCode__c, wido__Latitude__s, wido__Longitude__s FROM Branch__c];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}