force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>지역별 판매점</description>
    <label>판매점</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHistory__c/OrderHistory__c.object-meta.xml
<CustomObject>
    <label>주문내역</label>
    <nameField>
        <displayFormat>주문-{000000}</displayFormat>
        <label>주문번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHistory__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>주문내역</relationshipLabel>
    <relationshipName>AccHistoryNames</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>판매일자</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/OrderDetail__c.field-meta.xml
<CustomField>
    <fullName>OrderDetail__c</fullName>
    <inlineHelpText>제품명1: 수량, 제품명2: 수량, ...</inlineHelpText>
    <label>상세내역</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/SalesBranch__c.field-meta.xml
<CustomField>
    <fullName>SalesBranch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>판매점</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$User.Department</field>
            <operation>equals</operation>
            <valueField>Branch__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eIR000001fnLEYAY</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>주문내역</relationshipLabel>
    <relationshipName>SalesBranches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHistory__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>실판매금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PurchaseHistoryController.cls
public with sharing class PurchaseHistoryController {
    @AuraEnabled(cacheable=true)
    public static List<OrderHistory__c> getPurchaseHistory(String accountId) {
        // 주어진 AccountId에 일치하는 주문내역 조회하기
        return [
            SELECT Id, OrderDate__c, SalesBranch__r.Name, TotalPrice__c, OrderDetail__c, AccountName__c
            FROM OrderHistory__c
            WHERE AccountName__c = :accountId
            ORDER BY OrderDate__c DESC
        ];
    }
}