force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>지역별 판매점</description>
    <label>판매점</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/SalesRep__c.field-meta.xml
<CustomField>
    <fullName>SalesRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>판매사원</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>판매사원</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepngBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BranchRecordsController.cls
public with sharing class BranchRecordsController {
    @AuraEnabled(cacheable=true)
    public static List<Branch__c> getBranchRecordsForCurrentUser() {
        // 현재 로그인한 사용자의 Id 가져오기
        Id currentUserId = UserInfo.getUserId();
        
        // 현재 사용자와 일치하는 판매사원(SalesRep__c)이 있는 Branch__c 레코드 조회
        return [SELECT Id, Name, SalesRep__c FROM Branch__c WHERE SalesRep__c = :currentUserId];
    }
}