force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>제품 정보</description>
    <label>제품</label>
    <nameField>
        <label>제품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VoC__c/VoC__c.object-meta.xml
<CustomObject>
    <description>VoC 관련 Object</description>
    <label>VoC</label>
    <nameField>
        <displayFormat>VoC-{000000}</displayFormat>
        <label>VoC 번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VoC__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>account에서 고객명을 lookup해서 가져옴</description>
    <label>고객명</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AccountType__c</field>
            <operation>equals</operation>
            <value>구매고객</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>VoC</relationshipLabel>
    <relationshipName>VoC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VoC__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>상담시작일자(자동기입)</description>
    <label>상담시작일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VoC__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>상담내용</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VoC__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>상품명</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>아이디어패드 Slim3</fullName>
            </value>
            <value>
                <fullName>2024 그램15</fullName>
            </value>
            <value>
                <fullName>Sword GF76</fullName>
            </value>
            <value>
                <fullName>2023 그램15</fullName>
            </value>
            <value>
                <fullName>젠북 14 OLED</fullName>
            </value>
            <value>
                <fullName>2024 그램16</fullName>
            </value>
            <value>
                <fullName>갤럭시북4 프로</fullName>
            </value>
            <value>
                <fullName>갤럭시북3</fullName>
            </value>
            <value>
                <fullName>프레데터 Helios Neo</fullName>
            </value>
            <value>
                <fullName>아이디어패드 Slim1</fullName>
            </value>
            <value>
                <fullName>키보드 K560</fullName>
            </value>
            <value>
                <fullName>키보드 F99</fullName>
            </value>
            <value>
                <fullName>키보드 CK01</fullName>
            </value>
            <value>
                <fullName>키보드 G413</fullName>
            </value>
            <value>
                <fullName>키보드 GK893B</fullName>
            </value>
            <value>
                <fullName>마우스 SUPERLIGHT</fullName>
            </value>
            <value>
                <fullName>마우스 MX Master</fullName>
            </value>
            <value>
                <fullName>마우스 DeathAdder</fullName>
            </value>
            <value>
                <fullName>마우스 M1300QB</fullName>
            </value>
            <value>
                <fullName>마우스 G102</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VoC__c/fields/VoCType__c.field-meta.xml
<CustomField>
    <fullName>VoCType__c</fullName>
    <label>상담유형</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>단순문의</fullName>
            </value>
            <value>
                <fullName>고장</fullName>
            </value>
            <value>
                <fullName>교환</fullName>
            </value>
            <value>
                <fullName>환불</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VoCHistoryController.cls
public with sharing class VoCHistoryController {
    @AuraEnabled(cacheable=true)
    public static List<VoC__c> getVoCHistory(Id accountId) {
        return [SELECT CreatedDate__c, VoCType__c, Product__c, Description__c FROM VoC__c ];
        }

        @AuraEnabled(cacheable=true)
        public static List<VoC__c> getVoCs(Id accountId) {
            // accountId를 사용하여 특정 계정에 대한 상담 내역만 조회하도록 쿼리를 수정합니다.
            return [SELECT Id, AccountId__c, CreatedDate, VoCType__c, Product__c, Description__c
                    FROM VoC__c 
                    WHERE AccountId__c = :accountId
                    ORDER BY CreatedDate DESC]; // 최신 상담 내역부터 보여주도록 정렬
        }

        @AuraEnabled(cacheable=true)
        public static List<VoC__c> getVoCRecords(String customerName) {
            if(String.isBlank(customerName)) {
                return [SELECT Id, AccountId__r.Name, CreatedDate, VoCType__c, Product__c, Description__c FROM VoC__c];
            } else {
                return [SELECT Id, AccountId__r.Name, CreatedDate, VoCType__c, Product__c, Description__c
                        FROM VoC__c
                        WHERE AccountId__r.Name LIKE :('%' + customerName + '%')];
            }
        }

        @AuraEnabled(cacheable=true)
        public static List<VoC__c> getVoCDatas(String customerName) {
            if (String.isEmpty(customerName)) {
                // 고객명 검색어가 빈 경우 모든 VoC 레코드를 반환
                return [SELECT AccountId__r.Name, CreatedDate, VoCType__c, Product__c FROM VoC__c];
            } else {
                // 고객명 검색어가 있을 경우 검색 조건에 맞는 레코드만 반환
                return [SELECT AccountId__r.Name, CreatedDate, VoCType__c, Product__c FROM VoC__c WHERE AccountId__r.Name = :customerName];
            }
        }

        @AuraEnabled
        public static void updateVoC(VoC__c voc) {
            update voc; // 받은 VoC 객체를 업데이트합니다.
        }

        @AuraEnabled
    public static VoC__c saveVoCDetails(VoC__c voc) {
        try {
            upsert voc;
            return voc;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}