force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>제품 정보</description>
    <label>제품</label>
    <nameField>
        <label>제품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>제품사진</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>제품타입</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>노트북</fullName>
            </value>
            <value>
                <fullName>주변기기</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>제품가격</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductType__c/ProductType__c.object-meta.xml
<CustomObject>
    <label>제품유형</label>
    <nameField>
        <label>ProductType Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductBrowser.cls
public with sharing class ProductBrowser {

    @AuraEnabled(cacheable=true)
    public static List<Product__c> getProducts(String productId) {

        String query = '';

		//Base query
        query += 'SELECT Id, ProductType__c, Name, UnitPrice__c, Image_Url__c FROM Product__c';
        
        if(String.isNotEmpty(productId)) {
            query += ' WHERE Id = :productId';
        }
		
		return Database.query(query);
    }
}